### ISSUE TITLE
What are your maven (bintray) library includes?

### ISSUE THREAD

**Issue by steve-the-edwards** [walleth/keccak#12]
It looked like you were publishing on maven via bintray, so after reverse engineering the presumed include, I tried using the following:

repositories {
     `maven { url 'https://kotlin.bintray.com/komputing' }`
}

`implementation org.komputing:khash{-common/-native/_}:1.0.0-RC1`

But nothing resolved.  Do you have a maven include via bintray?

**Comment by ligi** [comment]
no - we are publishing this library via jitpack currently. 
@RiccardoM wanted to publish on bintray in the future (mainly for some multi-platform reason) AFAIR

**Comment by steve-the-edwards** [comment]
So is it

repositories {
`maven { url 'https://jitpack.io' }`
}

`implementation com.github.jitpack:khash{-common/-native/_}:1.0.0-RC1`

**Comment by ligi** [comment]
no - implementation com.github.komputing:khash{-common/-native/_}:1.0.0-RC1

you can also see the jitpack badge on the top of the readme - points to https://jitpack.io/#komputing/KHash

**Comment by steve-the-edwards** [comment]
Great thanks!
