### ISSUE TITLE
Implement sha512 for better security (and performance on 64bit arch)

### ISSUE THREAD

**Issue by friedger** [walleth/keccak#17]
Would an implementation of sha512 be in the scope of this project?

I am looking for an implementation of sha512/256, see for example https://eprint.iacr.org/2016/374.pdf

**Comment by ligi** [comment]
no I do not think it would be out of scope. Just wondering how much overlap with the existing sha256 module is - so if there should be another module or if it is an extension to the sha256 module

**Comment by friedger** [comment]
Due to 64bit integers, I would put sha512 and is derivations like sha512/256, sha512/224 and sha328 into a new module, similar to https://github.com/openssl/openssl/tree/master/crypto/sha

**Comment by ligi** [comment]
closed via #18 by @friedger :tada:
