### ISSUE TITLE
Bring back multiplatform support

### ISSUE THREAD

**Issue by friedger** [walleth/keccak#20]
I failed to include the library into a common source set of the multi platform project [KaMPkit](https://github.com/touchlab/KaMPKit)

The jvm part can be found in the android module

Steps to reproduce:
1. clone Kampkit
1. add jitpack repo: `maven(url = "https://jitpack.io")`
1. add khash depedency: `implementation("com.github.komputing:Khash:6fe00e9c11")`
1. add usage, e.g. in `BreedModel`:         
```
println("The quick brown fox jumps over the lazy dog".sha512())
```

The function can't be found. However, in `AndroidMain` ,e.g. in `PlatformAndroid`, the sha512 call can be correctly added.

Is this only a problem with the way of publications?

**Comment by ligi** [comment]
closed by @fullkomnun in #21
